# Generated by Django 2.1.1 on 2018-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
