# Generated by Django 2.1.2 on 2018-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0002_auto_20180903_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
