# Generated by Django 2.1.2 on 2018-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0004_auto_20181028_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_open_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
