# Generated by Django 2.1.2 on 2018-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0006_auto_20181028_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
