# Generated by Django 2.1.2 on 2018-10-31 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0007_auto_20181028_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='resubscribed_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pca.Registration'),
        ),
    ]
