# Generated by Django 2.1.2 on 2018-10-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0008_registration_resubscribed_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='resubscribed',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='resubscribed_at',
        ),
        migrations.AlterField(
            model_name='registration',
            name='resubscribed_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubscribed_to', to='pca.Registration'),
        ),
    ]
