# Generated by Django 2.1.7 on 2019-03-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0009_auto_20181031_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notification_sent_by',
            field=models.CharField(choices=[('LEG', '[Legacy] Sequence of course API requests'), ('WEB', 'Webhook'), ('SVC', 'Course Status Service'), ('ADM', 'Admin Interface')], default='LEG', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='resubscribed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubscribed_to', to='pca.Registration'),
        ),
    ]
