# Generated by Django 2.1.7 on 2019-03-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0010_auto_20190311_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('Open', 'O'), ('Closed', 'C')], max_length=16)),
                ('new_status', models.CharField(choices=[('Open', 'O'), ('Closed', 'C')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_sent', models.BooleanField()),
                ('request_body', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pca.Section')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='notification_sent_by',
            field=models.CharField(choices=[('LEG', '[Legacy] Sequence of course API requests'), ('WEB', 'Webhook'), ('SVC', 'Course Status Service'), ('ADM', 'Admin Interface')], default='LEG', max_length=16),
        ),
    ]
