# Generated by Django 2.1.7 on 2019-04-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0014_section_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_open_updated_at',
        ),
    ]
